### ISSUE TITLE
Release 0.7.2 - Experiment with new build system

### ISSUE THREAD

**Issue by marcioendo** [objectos/objectos-lang#1]
## Tasks

- [ ] Makefile: allow running the testing module
- [ ] Makefile: allow publishing snapshots?
- [ ] Makefile: allow deploying to Maven central?
